// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfd-qvg4lSQqFtsuctTpfO7gWWtlEpTw',
    appId: '1:915245993683:web:99e5bf98c971e8bcc50e26',
    messagingSenderId: '915245993683',
    projectId: 'campus-165e0',
    authDomain: 'campus-165e0.firebaseapp.com',
    storageBucket: 'campus-165e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkli3SmSBq7ROP0ET6y13vtys_d741T8',
    appId: '1:915245993683:android:f886e77abf948f3fc50e26',
    messagingSenderId: '915245993683',
    projectId: 'campus-165e0',
    storageBucket: 'campus-165e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Y_xWVBJwMB4W6U1X5m449UFEtXsAop8',
    appId: '1:915245993683:ios:8d8a4d17ef025c48c50e26',
    messagingSenderId: '915245993683',
    projectId: 'campus-165e0',
    storageBucket: 'campus-165e0.firebasestorage.app',
    iosBundleId: 'com.example.newsfeedFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Y_xWVBJwMB4W6U1X5m449UFEtXsAop8',
    appId: '1:915245993683:ios:8d8a4d17ef025c48c50e26',
    messagingSenderId: '915245993683',
    projectId: 'campus-165e0',
    storageBucket: 'campus-165e0.firebasestorage.app',
    iosBundleId: 'com.example.newsfeedFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFfd-qvg4lSQqFtsuctTpfO7gWWtlEpTw',
    appId: '1:915245993683:web:d314b122ed7b3fafc50e26',
    messagingSenderId: '915245993683',
    projectId: 'campus-165e0',
    authDomain: 'campus-165e0.firebaseapp.com',
    storageBucket: 'campus-165e0.firebasestorage.app',
  );
}
